sudo: required

language: python
services:
  - docker

before_install:
  - |
    docker build \
        --file _docker/allinone/Dockerfile \
        --tag ubiquitous/allinone .
script:
  - /bin/true
after_success:
  - |
    if [ "$TRAVIS_BRANCH" == 'better-containers' ]; then
      docker login -u="$DOCKER_USERNAME" --password-stdin <<<"$DOCKER_PASSWORD"
      docker push ubiquitous/allinone
    fi
