sudo: required
language: python
services:
  - docker

matrix:
  include:
    - before_script:
      - |
        curl -L https://bootstrap.saltstack.com | sudo sh -s -- -g https://github.com/LukeCarrier/salt.git -X git add-docker-slsbuild-extrafilerefs
        sudo apt install python-pip
        sudo salt-call --local pip.uninstall docker-py
        sudo salt-call --local pip.install docker
      - docker build _docker/ubuntu-python -t ubiquitous/ubuntu-python:16.04
      - sudo _docker/service/build -c ubiquitous/moodle-build -m moodle-componentmgr -m admin -m nvm
      - sudo _docker/service/build -c ubiquitous/moodle-web -m admin -m web-moodle -m web-default-release -f salt://web-base/macros.sls
      - sudo _docker/service/build -c ubiquitous/moodle-app -m admin -m app-moodle -m app-moodle-default-release -f salt://app-base/macros.sls
      - sudo _docker/service/build -c ubiquitous/db-pgsql -m admin -m db-pgsql
      - sudo _docker/service/build -c ubiquitous/selenium-hub -m admin -m selenium-hub
      - sudo _docker/service/build -c ubiquitous/selenium-node-chrome -m admin -m selenium-node-chrome
      - sudo _docker/service/build -c ubiquitous/selenium-node-firefox -m admin -m selenium-node-firefox
      script:
        - /bin/true
      after_success:
        - |
          if [ "$TRAVIS_BRANCH" == 'better-containers' ]; then
            containers=(
              ubiquitous/ubuntu-python:16.04

              ubiquitous/moodle-build
              ubiquitous/moodle-web
              ubiquitous/moodle-app

              ubiquitous/db-pgsql

              ubiquitous/selenium-hub
              ubiquitous/selenium-node-chrome
              ubiquitous/selenium-node-firefox
            )

            docker login -u="$DOCKER_USERNAME" --password-stdin <<<"$DOCKER_PASSWORD"
            for container in "${containers[@]}"; do
              docker push "$container"
            done
          fi
